{% set python_min = "3.10" %}
{% set name = "sparsestack" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sparsestack-{{ version }}.tar.gz
  sha256: 920d81f130f9390bcf491ddb60e5924d1223eaa63d818b8476b4eb57e461ed5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core
  run:
    - numba >=0.60.0
    - numpy >=2.0.0
    - python >={{ python_min }},<3.13
    - scipy >=1.14.1

test:
  imports:
    - sparsestack
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/florian-huber/stacked-sparse-array
  summary: Python library to handle stacks of sparse COO arrays efficiently.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hechth
    - florian-huber
