{% set name = "sparsestack" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sparsestack-{{ version }}.tar.gz
  sha256: 28f93bae1ab9aeec079d77020afd7859a6b3ad78f754be5e1f81feaad9528b6e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10,<3.13
    - poetry-core
  run:
    - numba >=0.60.0
    - numpy >=2.0.0
    - python >=3.10,<3.13
    - scipy >=1.14.1

test:
  imports:
    - sparsestack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/florian-huber/stacked-sparse-array
  summary: Python library to handle stacks of sparse COO arrays efficiently.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hechth
    - florian-huber
