{% set name = "sparsestack" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sparsestack-{{ version }}.tar.gz
  sha256: 5ab3e6c53cb3629dcc28d499e15b3c5f7c3dad3072381e4a1c2677a6333c3468

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numba
    - numpy
    - python >=3.7
    - scipy

test:
  imports:
    - sparsestack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/florian-huber/stacked-sparse-array
  summary: Python library to handle stacks of sparse COO arrays efficiently.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - florian-huber
